#@data/values
---
projectName: bpt-node-job
resourceType: Job
hasIngress: False
useHttp: False

volumes:
  - name: 'test-volume'
    persistentVolumeClaim:
      claimName: 'test-claim'
    mountPath: '/opt/data'
volumeClaims:
  - name: 'test-claim'
    storageClassName: gp2
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: '3Gi'
volumeStorages:
  - name: 'test-storage'
    storageClassName: gp2
    capacity:
      storage: '3Gi'
    accessModes:
      - ReadWriteOnce
